"""
Local template-based code generation engine.
No external APIs required — everything generated locally.
"""

import re
from typing import Optional


class LocalCodeGenerator:
    """
    Generates code locally using smart templates and pattern matching.
    Supports Python, JavaScript, TypeScript, Go, Rust, and Bash.
    No API keys required.
    """

    INTENT_PATTERNS = {
        'crud':      ['crud', 'database', 'model', 'repository', 'storage', 'db'],
        'auth':      ['auth', 'login', 'signup', 'jwt', 'token', 'password', 'session', 'oauth'],
        'api':       ['api', 'endpoint', 'route', 'rest', 'http', 'request', 'response', 'fetch'],
        'websocket': ['websocket', 'socket', 'realtime', 'real-time', 'chat', 'live'],
        'class':     ['class', 'object', 'model', 'entity', 'schema', 'struct'],
        'test':      ['test', 'spec', 'unittest', 'pytest', 'jest', 'assert'],
        'cli':       ['cli', 'command', 'argparse', 'argument', 'flag', 'subcommand'],
        'async':     ['async', 'await', 'coroutine', 'concurrent', 'parallel', 'task'],
        'function':  ['function', 'def', 'calculate', 'compute', 'process', 'helper', 'util'],
    }

    # ---------------------------------------------------------------------------
    # Public API
    # ---------------------------------------------------------------------------

    def generate(self, prompt: str, language: str = 'python') -> str:
        """Generate code for a given prompt and language."""
        intent = self._detect_intent(prompt)
        name = self._extract_name(prompt)
        return self._render(intent, name, prompt, language)

    # ---------------------------------------------------------------------------
    # Intent / name helpers
    # ---------------------------------------------------------------------------

    def _detect_intent(self, prompt: str) -> str:
        prompt_lower = prompt.lower()
        scores: dict = {}
        for intent, keywords in self.INTENT_PATTERNS.items():
            score = sum(1 for kw in keywords if kw in prompt_lower)
            if score:
                scores[intent] = score
        return max(scores, key=scores.get) if scores else 'function'

    def _extract_name(self, prompt: str) -> str:
        stop = {
            'a', 'an', 'the', 'to', 'for', 'with', 'that', 'create', 'make',
            'build', 'write', 'generate', 'add', 'implement', 'function', 'class',
            'api', 'endpoint', 'route', 'test', 'code', 'using', 'in', 'of', 'and',
        }
        words = re.sub(r'[^\w\s]', '', prompt).split()
        useful = [w for w in words if w.lower() not in stop and len(w) > 2]
        return '_'.join(useful[:3]).lower() if useful else 'main'

    # ---------------------------------------------------------------------------
    # Language dispatch
    # ---------------------------------------------------------------------------

    def _render(self, intent: str, name: str, prompt: str, language: str) -> str:
        lang = language.lower()
        if lang in ('python', 'py'):
            return self._python(intent, name, prompt)
        if lang in ('javascript', 'js', 'node'):
            return self._javascript(intent, name, prompt)
        if lang in ('typescript', 'ts'):
            return self._typescript(intent, name, prompt)
        if lang in ('go', 'golang'):
            return self._go(intent, name, prompt)
        if lang in ('rust', 'rs'):
            return self._rust(intent, name, prompt)
        if lang in ('bash', 'shell', 'sh'):
            return self._bash(intent, name, prompt)
        return self._python(intent, name, prompt)

    # ---------------------------------------------------------------------------
    # Python templates
    # ---------------------------------------------------------------------------

    def _python(self, intent: str, name: str, prompt: str) -> str:
        dispatch = {
            'crud':      self._python_crud,
            'auth':      self._python_auth,
            'api':       self._python_api,
            'websocket': self._python_websocket,
            'class':     self._python_class,
            'test':      self._python_test,
            'cli':       self._python_cli,
            'async':     self._python_async,
        }
        fn = dispatch.get(intent, self._python_function)
        return fn(name, prompt) if intent == 'function' else fn(name)

    def _python_function(self, name: str, prompt: str) -> str:
        return f'''# Generated python code: {prompt}

def main():
    """Entry point - generated by git-replica."""
    result = {name}()
    print(f"Result: {{result}}")


def {name}():
    """
    {prompt.capitalize()}

    Returns:
        The computed result.
    """
    # TODO: implement your logic here
    return None


if __name__ == "__main__":
    main()
'''

    def _python_class(self, name: str) -> str:
        class_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''# Generated python class - git-replica

from dataclasses import dataclass, field
from typing import Optional, List
from datetime import datetime


@dataclass
class {class_name}:
    """Data model for {name}."""

    id: int
    name: str
    description: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        return {{
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "created_at": self.created_at.isoformat(),
            "tags": self.tags,
        }}

    @classmethod
    def from_dict(cls, data: dict) -> "{class_name}":
        """Deserialize from dictionary."""
        return cls(
            id=data["id"],
            name=data["name"],
            description=data.get("description"),
            tags=data.get("tags", []),
        )

    def __repr__(self) -> str:
        return f"{class_name}(id={{self.id}}, name={{self.name!r}})"
'''

    def _python_crud(self, name: str) -> str:
        class_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''# Generated python CRUD - git-replica

from typing import Dict, List, Optional
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class {class_name}:
    id: int
    name: str
    data: dict = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)


class {class_name}Repository:
    """In-memory CRUD repository for {class_name}."""

    def __init__(self):
        self._store: Dict[int, {class_name}] = {{}}
        self._next_id = 1

    def create(self, name: str, data: Optional[dict] = None) -> {class_name}:
        """Create a new {name}."""
        item = {class_name}(id=self._next_id, name=name, data=data or {{}})
        self._store[self._next_id] = item
        self._next_id += 1
        return item

    def get(self, item_id: int) -> Optional[{class_name}]:
        """Get a {name} by ID."""
        return self._store.get(item_id)

    def list(self) -> List[{class_name}]:
        """List all {name}s."""
        return list(self._store.values())

    def update(self, item_id: int, **kwargs) -> Optional[{class_name}]:
        """Update a {name}."""
        item = self._store.get(item_id)
        if not item:
            return None
        for key, value in kwargs.items():
            if hasattr(item, key):
                setattr(item, key, value)
        return item

    def delete(self, item_id: int) -> bool:
        """Delete a {name} by ID."""
        if item_id in self._store:
            del self._store[item_id]
            return True
        return False


# --- Example usage ---
if __name__ == "__main__":
    repo = {class_name}Repository()

    item = repo.create("First item", {{"value": 42}})
    print(f"Created: {{item}}")

    items = repo.list()
    print(f"All items: {{items}}")

    updated = repo.update(item.id, name="Updated item")
    print(f"Updated: {{updated}}")

    deleted = repo.delete(item.id)
    print(f"Deleted: {{deleted}}")
'''

    def _python_auth(self, name: str) -> str:
        return '''# Generated python auth - git-replica

import hashlib
import secrets
import hmac
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Optional


@dataclass
class User:
    id: int
    username: str
    email: str
    password_hash: str
    created_at: datetime


class AuthManager:
    """Simple auth manager — replace with a proper backend for production."""

    SECRET_KEY = secrets.token_hex(32)
    TOKEN_TTL = timedelta(hours=24)

    def __init__(self):
        self._users: dict = {}
        self._tokens: dict = {}
        self._next_id = 1

    @staticmethod
    def hash_password(password: str) -> str:
        salt = secrets.token_hex(16)
        digest = hashlib.sha256(f"{salt}{password}".encode()).hexdigest()
        return f"{salt}:{digest}"

    @staticmethod
    def verify_password(password: str, password_hash: str) -> bool:
        try:
            salt, digest = password_hash.split(":")
            expected = hashlib.sha256(f"{salt}{password}".encode()).hexdigest()
            return hmac.compare_digest(expected, digest)
        except ValueError:
            return False

    def register(self, username: str, email: str, password: str) -> User:
        if username in self._users:
            raise ValueError(f"Username \'{username}\' already exists")
        user = User(
            id=self._next_id,
            username=username,
            email=email,
            password_hash=self.hash_password(password),
            created_at=datetime.utcnow(),
        )
        self._users[username] = user
        self._next_id += 1
        return user

    def login(self, username: str, password: str) -> Optional[str]:
        user = self._users.get(username)
        if not user or not self.verify_password(password, user.password_hash):
            return None
        token = secrets.token_urlsafe(32)
        self._tokens[token] = {
            "user_id": user.id,
            "username": username,
            "expires": datetime.utcnow() + self.TOKEN_TTL,
        }
        return token

    def validate_token(self, token: str) -> Optional[dict]:
        payload = self._tokens.get(token)
        if payload and payload["expires"] > datetime.utcnow():
            return payload
        return None

    def logout(self, token: str) -> bool:
        if token in self._tokens:
            del self._tokens[token]
            return True
        return False


# --- Example usage ---
if __name__ == "__main__":
    auth = AuthManager()
    user = auth.register("alice", "alice@example.com", "s3cr3t!")
    print(f"Registered: {user.username}")

    token = auth.login("alice", "s3cr3t!")
    print(f"Token: {token}")

    payload = auth.validate_token(token)
    print(f"Valid: {payload}")
'''

    def _python_api(self, name: str) -> str:
        return f'''# Generated python FastAPI endpoint - git-replica

from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

app = FastAPI(title="{name} API", version="1.0.0")


class {name.capitalize()}Create(BaseModel):
    name: str
    description: Optional[str] = None


class {name.capitalize()}Response(BaseModel):
    id: int
    name: str
    description: Optional[str]
    created_at: datetime


_store: dict = {{}}
_next_id = 1


@app.get("/", summary="Health check")
def health():
    return {{"status": "ok", "service": "{name}"}}


@app.get("/{name}s", response_model=List[{name.capitalize()}Response])
def list_{name}s():
    """List all {name}s."""
    return list(_store.values())


@app.post("/{name}s", response_model={name.capitalize()}Response, status_code=201)
def create_{name}(payload: {name.capitalize()}Create):
    """Create a new {name}."""
    global _next_id
    item = {{
        "id": _next_id,
        "name": payload.name,
        "description": payload.description,
        "created_at": datetime.utcnow(),
    }}
    _store[_next_id] = item
    _next_id += 1
    return item


@app.get("/{name}s/{{item_id}}", response_model={name.capitalize()}Response)
def get_{name}(item_id: int):
    """Get a {name} by ID."""
    item = _store.get(item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{name} not found")
    return item


@app.delete("/{name}s/{{item_id}}", status_code=204)
def delete_{name}(item_id: int):
    """Delete a {name}."""
    if item_id not in _store:
        raise HTTPException(status_code=404, detail="{name} not found")
    del _store[item_id]


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
'''

    def _python_websocket(self, name: str) -> str:
        return f'''# Generated python WebSocket server - git-replica

import asyncio
import json
from datetime import datetime
from typing import Set

try:
    import websockets
except ImportError:
    raise ImportError("Run: pip install websockets")


connected: Set = set()


async def handler(websocket, path="/"):
    """Handle incoming WebSocket connections."""
    connected.add(websocket)
    client = websocket.remote_address
    print(f"[+] {{client}} connected  (total: {{len(connected)}})")

    try:
        async for raw in websocket:
            try:
                message = json.loads(raw)
            except json.JSONDecodeError:
                message = {{"text": raw}}

            message["timestamp"] = datetime.utcnow().isoformat()
            message["from"] = str(client)

            # Broadcast to all connected clients
            broadcast = json.dumps(message)
            dead = set()
            for ws in connected:
                try:
                    await ws.send(broadcast)
                except websockets.ConnectionClosed:
                    dead.add(ws)
            connected.difference_update(dead)

    except websockets.ConnectionClosed:
        pass
    finally:
        connected.discard(websocket)
        print(f"[-] {{client}} disconnected (total: {{len(connected)}})")


async def main():
    HOST, PORT = "0.0.0.0", 8765
    print(f"{name} WebSocket server listening on ws://{{HOST}}:{{PORT}}")
    async with websockets.serve(handler, HOST, PORT):
        await asyncio.Future()


if __name__ == "__main__":
    asyncio.run(main())
'''

    def _python_test(self, name: str) -> str:
        class_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''# Generated python tests - git-replica

import pytest
from unittest.mock import MagicMock, patch


class Test{class_name}:
    """Test suite for {name}."""

    def setup_method(self):
        """Set up test fixtures."""
        # TODO: initialize your subject under test
        pass

    def teardown_method(self):
        """Clean up after each test."""
        pass

    def test_{name}_success(self):
        """Test the happy path."""
        # Arrange
        expected = True
        # Act
        result = True  # TODO: call your function/method
        # Assert
        assert result == expected

    def test_{name}_failure(self):
        """Test that errors are handled gracefully."""
        with pytest.raises(ValueError):
            raise ValueError("TODO: trigger a real error")

    def test_{name}_edge_case(self):
        """Test edge cases."""
        # TODO: test boundary conditions
        assert True

    @pytest.mark.parametrize("input_val,expected", [
        (1, True),
        (0, False),
        (-1, False),
    ])
    def test_{name}_parametrized(self, input_val, expected):
        """Parametrized test."""
        result = bool(input_val)
        assert result == expected


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

    def _python_cli(self, name: str) -> str:
        return f'''# Generated python CLI - git-replica

import click
import sys


@click.group()
@click.version_option("1.0.0")
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose output.")
@click.pass_context
def cli(ctx, verbose):
    """
    {name} — command-line tool generated by git-replica.
    """
    ctx.ensure_object(dict)
    ctx.obj["verbose"] = verbose


@cli.command()
@click.argument("name")
@click.option("--count", "-n", default=1, type=int, help="Number of times to greet.")
@click.pass_context
def hello(ctx, name, count):
    """Greet NAME."""
    for _ in range(count):
        click.echo(f"Hello, {{name}}!")
    if ctx.obj["verbose"]:
        click.echo(f"(greeted {{count}} time(s))")


@cli.command()
@click.option("--output", "-o", type=click.Path(), help="Output file path.")
@click.pass_context
def run(ctx, output):
    """Run the main task."""
    click.echo("Running {name}...")
    if output:
        with open(output, "w") as f:
            f.write("done\\n")
        click.echo(f"Output written to {{output}}")
    else:
        click.echo("Done.")


@cli.command()
@click.pass_context
def status(ctx):
    """Show current status."""
    click.echo(f"{name} status: OK")


if __name__ == "__main__":
    cli()
'''

    def _python_async(self, name: str) -> str:
        return f'''# Generated python async code - git-replica

import asyncio
from typing import List, Any


async def {name}(item: Any) -> Any:
    """
    Process {name} asynchronously.

    Args:
        item: The item to process.

    Returns:
        Processed result.
    """
    # Simulate async work
    await asyncio.sleep(0)
    return item


async def process_batch(items: List[Any], concurrency: int = 10) -> List[Any]:
    """Process a batch of items with bounded concurrency."""
    semaphore = asyncio.Semaphore(concurrency)

    async def bounded_{name}(item):
        async with semaphore:
            return await {name}(item)

    tasks = [bounded_{name}(item) for item in items]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    errors = [r for r in results if isinstance(r, Exception)]
    if errors:
        print(f"{{len(errors)}} error(s) encountered")

    return [r for r in results if not isinstance(r, Exception)]


async def main():
    items = list(range(20))
    results = await process_batch(items)
    print(f"Processed {{len(results)}} items")
    print(f"Results: {{results}}")


if __name__ == "__main__":
    asyncio.run(main())
'''

    # ---------------------------------------------------------------------------
    # JavaScript templates
    # ---------------------------------------------------------------------------

    def _javascript(self, intent: str, name: str, prompt: str) -> str:
        dispatch = {
            'crud':      self._js_crud,
            'auth':      self._js_auth,
            'api':       self._js_api,
            'class':     self._js_class,
            'test':      self._js_test,
            'async':     self._js_async,
        }
        fn = dispatch.get(intent, self._js_function)
        return fn(name, prompt) if intent == 'function' else fn(name)

    def _js_function(self, name: str, prompt: str) -> str:
        return f'''// Generated JavaScript: {prompt}

/**
 * {prompt.capitalize()}
 * @returns {{*}} The computed result
 */
function {name}() {{
  // TODO: implement your logic here
  return null;
}}

function main() {{
  const result = {name}();
  console.log(`Result: ${{result}}`);
}}

main();
'''

    def _js_class(self, name: str) -> str:
        class_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''// Generated JavaScript class - git-replica

class {class_name} {{
  /**
   * @param {{number}} id
   * @param {{string}} name
   * @param {{string|null}} description
   */
  constructor(id, name, description = null) {{
    this.id = id;
    this.name = name;
    this.description = description;
    this.createdAt = new Date();
    this.tags = [];
  }}

  toJSON() {{
    return {{
      id: this.id,
      name: this.name,
      description: this.description,
      createdAt: this.createdAt.toISOString(),
      tags: this.tags,
    }};
  }}

  static fromJSON(data) {{
    const obj = new {class_name}(data.id, data.name, data.description);
    obj.tags = data.tags || [];
    return obj;
  }}

  toString() {{
    return `{class_name}(#${{this.id}} ${{this.name}})`;
  }}
}}

function main() {{
  const item = new {class_name}(1, "Example");
  console.log(item.toString());
  console.log(JSON.stringify(item.toJSON(), null, 2));
}}

main();
'''

    def _js_crud(self, name: str) -> str:
        class_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''// Generated JavaScript CRUD repository - git-replica

class {class_name}Repository {{
  constructor() {{
    this._store = new Map();
    this._nextId = 1;
  }}

  create(name, data = {{}}) {{
    const item = {{ id: this._nextId++, name, data, createdAt: new Date() }};
    this._store.set(item.id, item);
    return item;
  }}

  get(id) {{
    return this._store.get(id) || null;
  }}

  list() {{
    return Array.from(this._store.values());
  }}

  update(id, updates) {{
    const item = this._store.get(id);
    if (!item) return null;
    Object.assign(item, updates, {{ id }});
    return item;
  }}

  delete(id) {{
    return this._store.delete(id);
  }}

  count() {{
    return this._store.size;
  }}
}}

function main() {{
  const repo = new {class_name}Repository();
  const item = repo.create("First", {{ value: 42 }});
  console.log("Created:", item);
  console.log("All:", repo.list());
  console.log("Updated:", repo.update(item.id, {{ name: "Updated" }}));
  console.log("Deleted:", repo.delete(item.id));
  console.log("Count:", repo.count());
}}

main();
'''

    def _js_auth(self, name: str) -> str:
        return '''// Generated JavaScript auth utility - git-replica
// Note: use bcrypt + proper JWT library in production

const crypto = require("crypto");

class AuthManager {
  constructor(secretKey = crypto.randomBytes(32).toString("hex")) {
    this.secretKey = secretKey;
    this.users = new Map();
    this.tokens = new Map();
    this.nextId = 1;
  }

  hashPassword(password) {
    const salt = crypto.randomBytes(16).toString("hex");
    const hash = crypto
      .createHmac("sha256", this.secretKey)
      .update(salt + password)
      .digest("hex");
    return `${salt}:${hash}`;
  }

  verifyPassword(password, stored) {
    const [salt, expected] = stored.split(":");
    const hash = crypto
      .createHmac("sha256", this.secretKey)
      .update(salt + password)
      .digest("hex");
    return hash === expected;
  }

  register(username, email, password) {
    if (this.users.has(username)) {
      throw new Error(`Username '${username}' already exists`);
    }
    const user = {
      id: this.nextId++,
      username,
      email,
      passwordHash: this.hashPassword(password),
      createdAt: new Date(),
    };
    this.users.set(username, user);
    return { id: user.id, username, email };
  }

  login(username, password) {
    const user = this.users.get(username);
    if (!user || !this.verifyPassword(password, user.passwordHash)) return null;
    const token = crypto.randomBytes(32).toString("hex");
    this.tokens.set(token, {
      userId: user.id,
      username,
      expiresAt: Date.now() + 86400000, // 24 h
    });
    return token;
  }

  validate(token) {
    const payload = this.tokens.get(token);
    if (payload && payload.expiresAt > Date.now()) return payload;
    return null;
  }

  logout(token) {
    return this.tokens.delete(token);
  }
}

const auth = new AuthManager();
auth.register("alice", "alice@example.com", "s3cr3t");
const token = auth.login("alice", "s3cr3t");
console.log("Token:", token);
console.log("Valid:", auth.validate(token));
'''

    def _js_api(self, name: str) -> str:
        return f'''// Generated Express.js API - git-replica

const express = require("express");
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

// In-memory store
const store = new Map();
let nextId = 1;

// Health
app.get("/", (req, res) => {{
  res.json({{ status: "ok", service: "{name}" }});
}});

// List
app.get("/{name}s", (req, res) => {{
  res.json(Array.from(store.values()));
}});

// Create
app.post("/{name}s", (req, res) => {{
  const {{ name: itemName, description }} = req.body;
  if (!itemName) return res.status(400).json({{ error: "name is required" }});
  const item = {{ id: nextId++, name: itemName, description, createdAt: new Date() }};
  store.set(item.id, item);
  res.status(201).json(item);
}});

// Get
app.get("/{name}s/:id", (req, res) => {{
  const item = store.get(Number(req.params.id));
  if (!item) return res.status(404).json({{ error: "Not found" }});
  res.json(item);
}});

// Update
app.put("/{name}s/:id", (req, res) => {{
  const id = Number(req.params.id);
  if (!store.has(id)) return res.status(404).json({{ error: "Not found" }});
  Object.assign(store.get(id), req.body, {{ id }});
  res.json(store.get(id));
}});

// Delete
app.delete("/{name}s/:id", (req, res) => {{
  const id = Number(req.params.id);
  if (!store.delete(id)) return res.status(404).json({{ error: "Not found" }});
  res.status(204).send();
}});

app.listen(PORT, () => {{
  console.log(`{name} API running at http://localhost:${{PORT}}`);
}});
'''

    def _js_test(self, name: str) -> str:
        return f'''// Generated Jest tests - git-replica

describe("{name}", () => {{
  beforeEach(() => {{
    // TODO: set up test fixtures
  }});

  afterEach(() => {{
    // TODO: clean up
  }});

  test("returns expected value on success", () => {{
    const result = true; // TODO: call your function
    expect(result).toBe(true);
  }});

  test("throws on invalid input", () => {{
    expect(() => {{
      throw new Error("TODO: trigger real error");
    }}).toThrow();
  }});

  test.each([
    [1, true],
    [0, false],
    [-1, false],
  ])("{name}(%i) → %s", (input, expected) => {{
    expect(Boolean(input)).toBe(expected);
  }});
}});
'''

    def _js_async(self, name: str) -> str:
        return f'''// Generated async JavaScript - git-replica

/**
 * Process {name} asynchronously.
 * @param {{*}} item
 * @returns {{Promise<*>}}
 */
async function {name}(item) {{
  // TODO: implement async logic
  await Promise.resolve();
  return item;
}}

/**
 * Process a batch with bounded concurrency.
 * @param {{Array}} items
 * @param {{number}} concurrency
 */
async function processBatch(items, concurrency = 10) {{
  const results = [];
  const queue = [...items];

  async function worker() {{
    while (queue.length > 0) {{
      const item = queue.shift();
      try {{
        results.push(await {name}(item));
      }} catch (err) {{
        console.error(`Error processing ${{item}}: ${{err.message}}`);
      }}
    }}
  }}

  await Promise.all(Array.from({{ length: concurrency }}, worker));
  return results;
}}

async function main() {{
  const items = Array.from({{ length: 20 }}, (_, i) => i);
  const results = await processBatch(items);
  console.log(`Processed ${{results.length}} items`);
  console.log("Results:", results);
}}

main().catch(console.error);
'''

    # ---------------------------------------------------------------------------
    # TypeScript templates
    # ---------------------------------------------------------------------------

    def _typescript(self, intent: str, name: str, prompt: str) -> str:
        dispatch = {
            'class': self._ts_class,
            'api':   self._ts_api,
            'crud':  self._ts_crud,
        }
        fn = dispatch.get(intent, self._ts_function)
        return fn(name, prompt) if intent == 'function' else fn(name)

    def _ts_function(self, name: str, prompt: str) -> str:
        return f'''// Generated TypeScript: {prompt}

function main(): void {{
  const result = {name}();
  console.log(`Result: ${{result}}`);
}}

function {name}(): unknown {{
  // TODO: implement your logic
  return null;
}}

main();
'''

    def _ts_class(self, name: str) -> str:
        class_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''// Generated TypeScript class - git-replica

interface I{class_name} {{
  id: number;
  name: string;
  description?: string;
  createdAt: Date;
  tags: string[];
}}

class {class_name} implements I{class_name} {{
  readonly id: number;
  name: string;
  description?: string;
  readonly createdAt: Date;
  tags: string[];

  constructor(id: number, name: string, description?: string) {{
    this.id = id;
    this.name = name;
    this.description = description;
    this.createdAt = new Date();
    this.tags = [];
  }}

  toJSON(): I{class_name} {{
    return {{
      id: this.id,
      name: this.name,
      description: this.description,
      createdAt: this.createdAt,
      tags: this.tags,
    }};
  }}

  static fromJSON(data: I{class_name}): {class_name} {{
    const obj = new {class_name}(data.id, data.name, data.description);
    obj.tags = data.tags ?? [];
    return obj;
  }}

  toString(): string {{
    return `{class_name}(#${{this.id}} ${{this.name}})`;
  }}
}}

const item = new {class_name}(1, "Example", "A sample item");
console.log(item.toString());
console.log(JSON.stringify(item.toJSON(), null, 2));
'''

    def _ts_api(self, name: str) -> str:
        return self._js_api(name).replace('// Generated Express.js API', '// Generated Express.js + TypeScript API')

    def _ts_crud(self, name: str) -> str:
        return self._js_crud(name)

    # ---------------------------------------------------------------------------
    # Go templates
    # ---------------------------------------------------------------------------

    def _go(self, intent: str, name: str, prompt: str) -> str:
        dispatch = {
            'api':   self._go_api,
            'class': self._go_struct,
            'crud':  self._go_crud,
        }
        fn = dispatch.get(intent, self._go_function)
        return fn(name, prompt) if intent == 'function' else fn(name)

    def _go_function(self, name: str, prompt: str) -> str:
        return f'''// Generated Go code: {prompt}
package main

import "fmt"

// {name} performs the requested operation.
func {name}() interface{{}} {{
\t// TODO: implement your logic
\treturn nil
}}

func main() {{
\tresult := {name}()
\tfmt.Printf("Result: %v\\n", result)
}}
'''

    def _go_struct(self, name: str) -> str:
        type_name = ''.join(w.capitalize() for w in name.split('_'))
        return f'''// Generated Go struct - git-replica
package main

import (
\t"fmt"
\t"time"
)

// {type_name} represents a {name}.
type {type_name} struct {{
\tID          int
\tName        string
\tDescription string
\tCreatedAt   time.Time
\tTags        []string
}}

// New{type_name} creates a new {type_name}.
func New{type_name}(id int, name, description string) *{type_name} {{
\treturn &{type_name}{{
\t\tID:          id,
\t\tName:        name,
\t\tDescription: description,
\t\tCreatedAt:   time.Now(),
\t\tTags:        []string{{}},
\t}}
}}

func (t *{type_name}) String() string {{
\treturn fmt.Sprintf("{type_name}(#%d %s)", t.ID, t.Name)
}}

func main() {{
\titem := New{type_name}(1, "Example", "A sample item")
\tfmt.Println(item)
}}
'''

    def _go_api(self, name: str) -> str:
        return f'''// Generated Go HTTP API - git-replica
package main

import (
\t"encoding/json"
\t"log"
\t"net/http"
\t"strconv"
\t"strings"
\t"sync"
\t"time"
)

type Item struct {{
\tID          int       `json:"id"`
\tName        string    `json:"name"`
\tDescription string    `json:"description,omitempty"`
\tCreatedAt   time.Time `json:"created_at"`
}}

type Store struct {{
\tmu     sync.RWMutex
\titems  map[int]Item
\tnextID int
}}

func NewStore() *Store {{ return &Store{{items: make(map[int]Item), nextID: 1}} }}

func (s *Store) Create(name, desc string) Item {{
\ts.mu.Lock()
\tdefer s.mu.Unlock()
\titem := Item{{ID: s.nextID, Name: name, Description: desc, CreatedAt: time.Now()}}
\ts.items[s.nextID] = item
\ts.nextID++
\treturn item
}}

func (s *Store) List() []Item {{
\ts.mu.RLock()
\tdefer s.mu.RUnlock()
\tout := make([]Item, 0, len(s.items))
\tfor _, v := range s.items {{
\t\tout = append(out, v)
\t}}
\treturn out
}}

func jsonResp(w http.ResponseWriter, status int, v interface{{}}) {{
\tw.Header().Set("Content-Type", "application/json")
\tw.WriteHeader(status)
\tjson.NewEncoder(w).Encode(v)
}}

func main() {{
\tstore := NewStore()
\tmux := http.NewServeMux()

\tmux.HandleFunc("/{name}s", func(w http.ResponseWriter, r *http.Request) {{
\t\tswitch r.Method {{
\t\tcase http.MethodGet:
\t\t\tjsonResp(w, 200, store.List())
\t\tcase http.MethodPost:
\t\t\tvar body struct {{ Name, Description string }}
\t\t\tjson.NewDecoder(r.Body).Decode(&body)
\t\t\tjsonResp(w, 201, store.Create(body.Name, body.Description))
\t\tdefault:
\t\t\tw.WriteHeader(405)
\t\t}}
\t}})

\tmux.HandleFunc("/{name}s/", func(w http.ResponseWriter, r *http.Request) {{
\t\tidStr := strings.TrimPrefix(r.URL.Path, "/{name}s/")
\t\t_, err := strconv.Atoi(idStr)
\t\tif err != nil {{
\t\t\tw.WriteHeader(400)
\t\t\treturn
\t\t}}
\t\tw.WriteHeader(204)
\t}})

\tmux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {{
\t\tjsonResp(w, 200, map[string]string{{"status": "ok", "service": "{name}"}})
\t}})

\tlog.Println("{name} API listening on :8080")
\tlog.Fatal(http.ListenAndServe(":8080", mux))
}}
'''

    def _go_crud(self, name: str) -> str:
        return self._go_struct(name)

    # ---------------------------------------------------------------------------
    # Rust templates
    # ---------------------------------------------------------------------------

    def _rust(self, intent: str, name: str, prompt: str) -> str:
        return f'''// Generated Rust code: {prompt}

fn main() {{
    let result = {name}();
    println!("Result: {{:?}}", result);
}}

/// {prompt.capitalize()}
fn {name}() -> Option<i64> {{
    // TODO: implement your logic
    None
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_{name}_returns_none() {{
        assert_eq!({name}(), None);
    }}
}}
'''

    # ---------------------------------------------------------------------------
    # Bash templates
    # ---------------------------------------------------------------------------

    def _bash(self, intent: str, name: str, prompt: str) -> str:
        return f'''#!/usr/bin/env bash
# Generated shell script: {prompt}
set -euo pipefail

# ---------------------------------------------------------------------------
# {name.upper()}
# {prompt.capitalize()}
# ---------------------------------------------------------------------------

LOG_LEVEL="${{LOG_LEVEL:-info}}"

info()  {{ echo "[INFO]  $*"; }}
warn()  {{ echo "[WARN]  $*" >&2; }}
error() {{ echo "[ERROR] $*" >&2; exit 1; }}

{name}() {{
    # TODO: implement your logic here
    info "{name}: starting"
    local result=0
    return $result
}}

main() {{
    {name} "$@"
    info "Done."
}}

main "$@"
'''
